### PR TITLE
Fix/497 button styling fix

### LINKED ISSUE #497: Formatting button issues in gtfs.staging.org
## **Feature request**

**Is your feature request related to a problem? Please describe.**
In order to unblock #493, some formatting issues with the buttons on gtfs.staging.org need to be adjusted.

cc @eliasmbd @Sergiodero

### PR DESCRIPTION
**Pull request by Alessandro100**
Styling fixes to pages outside of the landing page to match the theme

Flex
image

Fares page
imageFlex page

Why use gtfs
image

Cookies
image

Footer
image

### CODE REVIEW

**Comment by fredericsimard** [comment]
LGTM! Tested locally and everything looks great.

@Sergiodero Do you want to double-check?

**Review by fredericsimard — APPROVED** [review]
LGTM! Tested locally and everything looks great.

@Sergiodero Do you want to double-check?

**Comment by Sergiodero** [comment]
Thanks for working on this Alessandro! This looks good on my end! I think we can let @eliasmbd have one final look before merging if this works with your availability @Alessandro100

**Review by Sergiodero — APPROVED** [review]

**Review by eliasmbd — APPROVED** [review]
LGTM

**Comment by eliasmbd** [comment]
I merged it, I just noticed that the following external link icon is really detached from the text: 
Screenshot 2024-06-21 at 11 35 30 AM
Screenshot 2024-06-21 at 11 34 53 AM

I doesnt bother me too much but it almost feels like a separate item.

**Comment by Alessandro100** [comment]
> I merged it, I just noticed that the following external link icon is really detached from the text: Screenshot 2024-06-21 at 11 35 30 AM Screenshot 2024-06-21 at 11 34 53 AM
> 
> I doesnt bother me too much but it almost feels like a separate item.

Thats a quick fix, we can make a ticket for it

**Comment by fredericsimard** [comment]
@Alessandro100 Your screenshots are "not found", which is a nice way to illustrate the problem of missing images LOL

I think that if we could fix this easily, we should before translation begins. Besides the links audit and unless I'm mistaken that's all that's left to fix before work can begin on translations.

**Pull request merged**
