### PR TITLE
Restore_previous_Resources_structure

### PR DESCRIPTION
**Pull request by Sergiodero**
This change restores the Resources section to its previous version (the one currently used in gtfs.org). This also removes the new structure from the navigation without deleting its files. 

The next step for this PR to be completed is to review all links, add notes to the ones deprecated and remove the ones broken.

### CODE REVIEW

**Comment by isabelle-dr** [comment]
> This also removes the new structure from the navigation without deleting its files.

Could you clarify what this means?

> The next step for this PR to be completed is to review all links, add notes to the ones deprecated and remove the ones broken.

Isn't this more an issue to tackle in https://github.com/MobilityData/awesome-transit

**Comment by Sergiodero** [comment]
> Could you clarify what this means?

It means that I'm not deleting the files that we put together in the design sprint for the resource Library, they are still in the repo, but they are not accessible/visible. I'm assuming they could be useful when we eventually tackle this section in a next iteration.

> Isn't this more an issue to tackle in https://github.com/MobilityData/awesome-transit

You're probably right, but still all the changes should be reflected in GTFS.org unless we want to only redirect to the Awesome Transit list, we can discuss this further in our next sync.

**Comment by isabelle-dr** [comment]
> It means that I'm not deleting the files that we put together in the design sprint for the resource Library, they are still in the repo, but they are not accessible/visible. 

I'd prefer having a branch called `design sprint resources` with the files there, but deleting them from `main`.

>  but still all the changes should be reflected in GTFS.org unless we want to only redirect to the Awesome Transit list, we can discuss this further in our next sync.

I might be missing something, I understood that what is in scope for this gtfs.org iteration is to revert to the original resource page (which mirrors the awesome transit list)

**Comment by Sergiodero** [comment]
> I might be missing something, I understood that what is in scope for this gtfs.org iteration is to revert to the original resource page (which mirrors the awesome transit list)

You're right, so I think we can merge this as is. As for the "hidden" files, there are still some of these files from different sections hanging around, we can do another PR to delete all of them after we move them to that `design sprint resources` branch you are proposing. What do you think?

**Comment by isabelle-dr** [comment]
This seems reasonable. 
Thanks for working on this @Sergiodero! Approving this PR

**Review by isabelle-dr — APPROVED** [review]

**Pull request merged**
