### PR TITLE
FR review Getting Started section translation

### PR DESCRIPTION
**Pull request by Sergiodero**
This PR continues the work done in PR #97 to finalize the French translation review in the Getting started Section

Section | Page | Formatting | Correct Translations
-- | -- | -- | -- 
Getting started | What is GTFS? | ✅ | ✅
Getting started | Why use GTFS? | ✅ | ✅
Getting started | Create | ✅ | ✅
Getting started | Validate | ✅ | ✅
Getting started | Publish | ✅ | ✅
Getting started | Features Overview | ✅ | ✅
Getting started | Base Features | ✅ | ✅
Getting started | Base add-ons Features | ✅ | ✅
Getting started | Accesibility Features | ✅ | ✅
Getting started | Fares Features | ✅ | ✅
Getting started | Pathways Features | ✅ | ✅
Getting started | Flexible services Features | ✅ | ✅
Getting started | Example GTFS feed | ✅ | ✅

### CODE REVIEW

**Comment by Sergiodero** [comment]
FYI @richfab I pushed a commit to fix a broken anchor, I'll keep looking for potential broken links and formatting errors and add them to this branch. Please push all changes as you finish with each individual page review. Thanks!

**Comment by richfab** [comment]
@Sergiodero Completed 🎉

**Comment by richfab** [comment]
For future reference, here are the most common translation mistakes that I observed: https://github.com/MobilityData/elrond.gtfs.org/pull/97#issuecomment-2265018167

**Comment by Sergiodero** [comment]
Thanks so much @richfab! @eliasmbd, @fredericsimard can one of you help me reviewing/merging? I can't do it since I created the PR. Thanks!

**Review by fredericsimard — APPROVED** [review]
LGTM!

**Pull request merged**
