### PR TITLE
Merge staging into main

### PR DESCRIPTION
**Pull request by fredericsimard**
Make staging the main branch for this fork.

### CODE REVIEW

**Review by Alessandro100 — APPROVED** [review]
looks good to me

**Review by Sergiodero — APPROVED** [review]
I ran it locally and looks like the changes are being displayed correctly, so LGTM!

**Comment by isabelle-dr** [comment]
I solved the conflicts on the Best Practice doc, but I am not sure how to solve it on the .yml file, this seems to be related to the translations. 

One question: do we want all translations removed from this branch so we can add them back in a more organized way?

**Comment by fredericsimard** [comment]
@isabelle-dr Unless you resolve all conflicts, none of the changes are saved. I'd need to know how to fix the only conflict I can't resolve in order to merge.

This part, to be specific, rows 236-253:

```
<<<<<<< staging
Good question! The process of examining the Specification, data usage and needs did indeed trigger some changes to the Specification (see [closed pull requests in GitHub](https://github.com/google/transit/pulls?q=is%3Apr+is%3Aclosed)). 
Specification reference amendments are subject to a higher bar of scrutiny and comment than the Best Practices. Certain Best Practices are being merged into the spec based on their level of adoption and community consensus. Eventually, all GTFS Best Practices could become part of the core GTFS Reference.

### How to check for conformance with these Best Practices?

The Canonical GTFS Schedule Validator checks for compliance against these Best Practices. You can find more about this validation tool on the [validate page](https://gtfs.org/schedule/validate/).
=======
### Why not just change the GTFS reference?

Good question! The process of examining the Specification, data usage and needs did indeed trigger some changes to the Specification. Since then, certain Best Practices have been merged into the spec based on their level of adoption and community consensus. 
Eventually, the GTFS Best Practices will become part of the core GTFS Reference. To contribute to this effort, please go to the [GTFS Reference GitHub repository](https://github.com/google/transit/), or contact [specifications@mobilitydata.org](mailto:specifications@mobilitydata.org).

### How to check for conformance with these Best Practices?

The Canonical GTFS Schedule Validator checks for compliance against the GTFS Best Practices that can be automatically verified. Each [warning](https://gtfs-validator.mobilitydata.org/rules.html#WARNING-table) corresponds to recommendations that are either explicitly suggested by the GTFS Schedule Reference, using the term “recommend” or “should,” or mentioned in this document.
You can find more about this validation tool on the [validate page](https://gtfs.org/schedule/validate/).
>>>>>>> main
```

**Comment by fredericsimard** [comment]
> One question: do we want all translations removed from this branch so we can add them back in a more organized way?

I think yes, there are too many changes and it's safer to assume all languages need to be translated again.

**Comment by Sergiodero** [comment]
Thanks @fredericsimard, regarding the conflicts in the best practices document please use the following text for the conflict on lines 236-256:

> ### Why not just change the GTFS reference?
> Good question! The process of examining the Specification, data usage and needs did indeed trigger some changes to the Specification. Since then, certain Best Practices have been merged into the spec based on their level of adoption and community consensus. 
> Eventually, the GTFS Best Practices will become part of the core GTFS Reference. To contribute to this effort, please go to the [GTFS Reference GitHub repository](https://github.com/google/transit/), or contact [specifications@mobilitydata.org](mailto:specifications@mobilitydata.org).
>### How to check for conformance with these Best Practices?
>The Canonical GTFS Schedule Validator checks for compliance against the GTFS Best Practices that can be automatically verified. Each [warning](https://gtfs-validator.mobilitydata.org/rules.html#WARNING-table) corresponds to recommendations that are either explicitly suggested by the GTFS Schedule Reference, using the term “recommend” or “should,” or mentioned in this document.
> You can find more about this validation tool on the [validate page](https://gtfs.org/schedule/validate/).

And this one for the conflict on lines 259-271:

> ### What should I do if I notice a GTFS data feed does not conform to the GTFS Best Practices?
> Identify the contact for the feed, using the `feed_contact_email` or `feed_contact_url` fields in [feed_info.txt](https://gtfs.org/schedule/reference/#feed_infotxt) if they are provided, or looking up contact information on the transit agency or feed producer website. When communicating the issue to the feed producer, link to the specific GTFS Best Practice that isn't being followed using this document (See ["Linking to this Document"](#linking-to-this-document)) or [the appropriate warning](https://gtfs-validator.mobilitydata.org/rules.html#WARNING-table) in the Canonical GTFS Schedule Validator if available.
> ### How can I get involved?

In both cases the second text is the correct one, LMK if you have any questions!

**Comment by fredericsimard** [comment]
All done, thanks!

**Pull request merged**
