### PR TITLE
Update features to latest mapping

### PR DESCRIPTION
**Pull request by isabelle-dr**
@Sergiodero I had a first go at updating the site with the latest mapping we landed on last week.
Feel free to contribute to this branch!

In this PR:
- [x] Make feature adjustments based on the latest mapping (see below)
- [x] Change "Pre-Requirement" to "Prerequisite", I think this term best serves what we're trying to transmit.
- [x] Place the prerequisites after the files & fields included table and on a single line when there is only one
- [x] Remove prerequisites from the Base group. I think we're clear on the site that the Base features are all needed to create a functioning dataset. 
- [x] Smaller clean-up, editorial changes and simplifications of descriptions
- [x] Update the "Overview" page
- [x] Update the .yml file

Screenshot 2024-05-12 at 7 18 33 PM

### CODE REVIEW

**Comment by isabelle-dr** [comment]
@Sergiodero this is ready for review!

**Comment by Sergiodero** [comment]
Thanks for this! I've just added a new commit editing the .yml file since the navigation wasn't updated. I took a quick look and the first thing that I'm noticing is that the rendering of the boxes for each feature in the overview page is a bit off (see image below). 

image


I think a potential solution would be to update all descriptions to have between 60 and 70 characters (including spaces), that way the space would be more evenly distributed with two-line texts. 

I'll continue with a more in-depth review tomorrow.

**Review by Sergiodero — CHANGES_REQUESTED** [review]
I finalized my review and made some changes (three types):

- Fixed the last card in the overview page which wasn't rendering properly 
- Fixed a lot of problematic links (my bad for not catching this earlier)
- Fixed the order for a few Pre-requirements that were before the table of fields and files and not after

After this I only have two general comments:

- I would keep formatting consistent across all pages by always listing prerequisites in bullet point form even if there is only one prerequisite associated with the feature.
- I would add prerequisites back to the Base features in the same way that we previously did, using the text "Prerequisites: all other Base features"

These are small changes that I can take on if you agree with them.

On the other hand, I spend some time today finding ways to predefine the width of all cards in the overview page, but had no success, seems like there is no way to override the adjustment of the width to the length of the content. Considering this, could you help me revisiting the descriptions for all features in the overview page so that they all be around 70 characters? I think this is the most important change so lmk if you have capacity. Thanks!

**Comment by isabelle-dr** [comment]
Thank you so much for all these fixes @Sergiodero!

> I would keep formatting consistent across all pages by always listing prerequisites in bullet point form even if there is only one prerequisite associated with the feature.


Addressed in https://github.com/MobilityData/elrond.gtfs.org/pull/22/commits/7b0583b00a4c636797d16c15aa1d1425d925d409 and https://github.com/MobilityData/elrond.gtfs.org/pull/22/commits/cc3c770549b09438a04f5d6062600896aa86d508

> I would add prerequisites back to the Base features in the same way that we previously did, using the text "Prerequisites: all other Base features"

Addressed in https://github.com/MobilityData/elrond.gtfs.org/pull/22/commits/5d9f85b18ed6d098cf5dadfddccf30fc55915de2

> could you help me revisit the descriptions for all features in the overview page so that they all be around 70 characters?

I added spaces to the feature descriptions in https://github.com/MobilityData/elrond.gtfs.org/pull/22/commits/140cd1b0964972f3e7b15e4cfa6e045878742538 so they are all 70 chars long. Is it better?

**Comment by Sergiodero** [comment]
Thanks @isabelle-dr! Fixes are looking good for the first two points, thanks for working on this! 

Unfortunately the space quick-fix for the cards in the overview page didn't work (see image below), I can't think of any other workaround other than writing longer descriptions, we can use the previous ones which were a bit longer but I'm not sure how do you feel about that. Thoughts?

Screenshot 2024-05-24 at 9 32 28 AM

**Comment by isabelle-dr** [comment]
@Sergiodero I've updated the descriptions. 
Feel free to make changes directly until the rendering is right.

**Review by Sergiodero — APPROVED** [review]
Thanks @isabelle-dr, I did some final adjustments and I think we're ready to merge!

Screenshot 2024-05-27 at 5 24 14 PM

**Pull request merged**
