### PR TITLE
Feat/512 UI touchups

### PR DESCRIPTION
**Pull request by Alessandro100**
Changes in this PR

Landing
- Small animations added
- Responsive styling updated
- General style updates

Header
- Logo image quality improved
- Improved mobile styling

General
- Buttons that point to external links: fixed styling
- Removed unused image assets

### CODE REVIEW

**Review by fredericsimard — APPROVED** [review]
LGTM!

**Review by Sergiodero — APPROVED** [review]
LGTM! The animations in the LP look good!

There's only one thing that I noticed: the icon displayed in my browser tab is different than the new GTFS one (yellow one with the 3 dots):

Screenshot 2024-08-20 at 4 24 55 PM



I think this was fixed already in another PR, maybe it'll be fixed when we merge?

**Comment by Alessandro100** [comment]
> LGTM! The animations in the LP look good!
> 
> There's only one thing that I noticed: the icon displayed in my browser tab is different than the new GTFS one (yellow one with the 3 dots):
> 
> Screenshot 2024-08-20 at 4 24 55 PM
> I think this was fixed already in another PR, maybe it'll be fixed when we merge?

If I recall, @fredericsimard you mentioned that you were taking care of the favicon right?

**Comment by fredericsimard** [comment]
@Alessandro100 @Sergiodero Yes! It's in the [ES-and-FR...](https://github.com/MobilityData/elrond.gtfs.org/tree/ES-and-FR-translation-implementation-20240718) branch.

**Pull request merged**
